theme: jekyll-theme-cayman
title: Hadoop2Databricks
description: This Repository consists of all the custom scripts needed to migrate from Infoworks Onprem environment to Infoworks Databricks environment
